<a href="https://colab.research.google.com/github/ma2ura/Matsuura_Seminar_2021/blob/master/semi2021spring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 数値計算ためのライブラリ(モジュールともいう) NumPy(ナンパイ)を学ぶ。

まずはnumpyライブラリを読み込む。読み込む場合は，
import ライブラリ名 as 略名
ライブラリ名は何度も出てくるので，略せるようしておく。

In [ ]:
import numpy as np

これで`numpy`を読み込んだので，次はベクトルを作る。ライブラリ内のモジュール関数`array()`を用いる。

In [ ]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

`type()`でデータの型をみる。

In [ ]:
type(arr)

numpy.ndarray

次は行列を作る。モジュール関数arrayを使うところはベクトルと同じ。
4つのベクトルを組み合わせて$4 \times 4$行列を作り，`mat`に代入

In [ ]:
mat = np.array(
    [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
    ]
)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
print(type(arr))
print(type(mat))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# 一次元配列：要素の抽出

Pythonでは配列(ベクトル)の添え字は0から始まる。

In [ ]:
arr[1] # 10じゃなく20

20

In [ ]:
arr[[0,1,3]]

array([10, 20, 40])

In [ ]:
arr[1:4]

array([20, 30, 40])

# 行列：要素の抽出

`[行のインデックス，列のインデックス]`とする。$3\times 3$の行列の一番左上の数値は。`mat[0,0]`となる。

In [ ]:
mat[0,0]

1

第`i`行の抽出の書き方

In [21]:
r0 = mat[0, :] # 1行
r0

array([1, 2, 3, 4])

In [20]:
mat[1:3, : ] # 2と3行

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mat[: , 1] # 列は2列目

In [19]:
mat[:, 1:3] # 2と3列

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# 行列計算

行列の演算は統計学や機械学習で良く出てくるので，勉強しておくとよい。

In [23]:
m1 = np.array([[1, 1],[1, 1]])
m2 = np.array([[2, 2],[2, 2]])

In [24]:
m1 + m2 # 行列の和

array([[3, 3],
       [3, 3]])

In [25]:
m2 - m1 # 行列の差

array([[1, 1],
       [1, 1]])

In [26]:
10 * m1 # 定数倍

array([[10, 10],
       [10, 10]])

In [27]:
m1 / 2 # 行列に割り算はないので，1/2で定数倍と同じ意味

array([[0.5, 0.5],
       [0.5, 0.5]])

## 行列の積

In [28]:
m1 * m2 # 要素同士のかけ算

array([[2, 2],
       [2, 2]])

In [29]:
m1 @ m2 # 数学で学ぶ行列の積

array([[4, 4],
       [4, 4]])

In [30]:
np.dot(m1,m2) # モジュラー関数`dot`だとこう書く

array([[4, 4],
       [4, 4]])

## 転置行列

$2 \times 3$行列を作る

In [32]:
m3 = np.array([[1,2,3],[4,5,6]])
m3

array([[1, 2, 3],
       [4, 5, 6]])

メソッド`transpose()`を使って転置行列にする。
変数`m3`の後ろにドットを置いてメソッドを使う。

In [33]:
m3.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
m3.T # これでもOK

array([[1, 4],
       [2, 5],
       [3, 6]])

## 逆行列

逆行列の計算はよく出てくるし，計算が面倒なので，パソコンにやらせたい演算No.1です。

In [35]:
from numpy.linalg import inv

In [38]:
m4 = np.array([[1, 2],[3, 4]])
m4

array([[1, 2],
       [3, 4]])

In [39]:
inv(m4)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

逆行列を用いて連立方程式を解く。通称，クラメールの法則
$$
ax + bz + cy  = m\\
ex + fz + gy  = n\\
hx +iz +  jy = o
$$
という未知変数が$x, y, z$の連立方程式があるとする。これを行列表記すると，
$$
\left (
  \begin{array}
  1a & b & c\\
  e & f & g\\
  h & i & j\\
  \end{array}  
\right )
\left (
  \begin{array}
  1x \\
  y\\
  z
  \end{array}
\right ) = 
\left (
  \begin{array}
  1m \\
  n\\
  0
  \end{array}
\right ) 
$$
となり，次のように表記することにする。
$$
\boldsymbol{Ax} = \boldsymbol{b} 
$$
両辺に左から$A$の逆行列$A^{-1}$を乗じると，
$$
\boldsymbol{A^{-1}Ax} = \boldsymbol{A^{-1}b} 
$$
となり，$\boldsymbol{A^{-1}A}$は単位行列$I$となるため，
$$
\boldsymbol{x} = \boldsymbol{A^{-1}b} 
$$
となり，未知数が求められる。

たとえば，
$$
2 x_1 + 3x_2 = 1\\
5x_1 + x_2 = 3
$$
を解いてみる。行列にすると
$$
\left (
  \begin{array}
  12 & 3 \\
  5 & 1 
  \end{array}  
\right )
\left (
  \begin{array}
  1x_1 \\
  x_2
  \end{array}
\right ) = 
\left (
  \begin{array}
  11 \\
  3
  \end{array}
\right )
$$
左から逆行列をかける。
$$
\left (
  \begin{array}
  1x_1 \\
  x_2
  \end{array}
\right ) = 
\left (
  \begin{array}
  12 & 3 \\
  5 & 1 
  \end{array}  
\right )^{-1}
\left (
  \begin{array}
  11 \\
  3
  \end{array}
\right )
$$

In [47]:
a = np.array([[2,3],[5,1]])
a

array([[2, 3],
       [5, 1]])

In [48]:
ia = inv(a)

In [49]:
b = np.array([[1],[3]])

In [50]:
ia@b

array([[ 0.61538462],
       [-0.07692308]])